### ISSUE TITLE
Questions about BitOPs

### ISSUE THREAD

**Issue by hibyeqt** [Sheldon04/CABM-pytorch#2]
I am highly interested in innovative ideas and performance as well. 
However, I have a few questions regarding BitOPs. It seems that the formula for calculating BitOPs in Table 2 of the CABM paper is 
**EDSR-CABM_x4 BitOPs (3.75G) = 114.23G x (5.80 / 32) x (5.80 / 32).** 
114.23G for 32bit model
5.80 / 32 for activation
5.80 / 32 for weight
However, the paper and code mention the use of fixed-precision for weights. 
Could you please explain how the BitOPs are calculated?

**Comment by Sheldon04** [comment]
Thank you for your question! 
Corresponding descriptions will be added in subsequent versions of our arXiv paper.

**Comment by hibyeqt** [comment]
Thank you for your prompt response. 
However, it seems that the weights in the code are 8-bit fixed precision. 
Could you provide the code with mixed-precision weights used in the performance of the paper?  
In addition, when I attempted training myself, I achieved different results (5.63 bit / 25.85 PSNR) compared to the paper's reported results (5.80bit / 25.95 PSNR). 
To ensure a fair performance comparison, could you also provide the pretrained weights?

**Comment by Sheldon04** [comment]
1. PR is welcomed to add support for mixed precision weights.
2. This is a simplified version of our code. To reproduce the results in the paper, you may take sampling strategies which is mentioned in README.md. And you should also check the whole training pipeline, make sure that all the models are trained well to get a better result.
