### ISSUE TITLE
where can I find EDSR-[4]-['div2k_valid'].json?

### ISSUE THREAD

**Issue by dunanyang** [Sheldon04/CABM-pytorch#4]
When I run the code, I encounter this below error:
with open(f"{args.model}-[4]-['div2k_valid'].json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: "EDSR-[4]-['div2k_valid'].json"
I'm looking forward for your reply.

**Comment by Sheldon04** [comment]
Before you test the models, you should first run step 1-3 to train the models, and then in step4 you will use the pretrained models to generate the bit config files.
If you do not have resources to reproduce, you may refer to [CADyQ(PyTorch)](https://github.com/Cheeun/CADyQ) to download the pretrained weights.
Thanks for support~

**Comment by dunanyang** [comment]
确实是没有这个文件的，还是代码bug呢？

**Comment by Sheldon04** [comment]
您好！
这个文件我没有放上去，您可以先读一下论文，然后按照步骤训练模型，到第四步的时候，运行对应的脚本就可以生成这个文件了！
这里是保存这个文件的代码：
https://github.com/Sheldon04/CABM-pytorch/blob/07c2707abfc132a7677a46d7a1aa8d03d7eff4c0/main_getconfig.py#L683

**Comment by dunanyang** [comment]
你好，是不是可以直接把对应的那个代码注释掉了？

**Comment by 427cll** [comment]
> 您好！ 这个文件我没有放上去，您可以先读一下论文，然后按照步骤训练模型，到第四步的时候，运行对应的脚本就可以生成这个文件了！ 这里是保存这个文件的代码：
> 
> [CABM-pytorch/main_getconfig.py](https://github.com/Sheldon04/CABM-pytorch/blob/07c2707abfc132a7677a46d7a1aa8d03d7eff4c0/main_getconfig.py#L683)
> 
> Line 683 in [07c2707](/Sheldon04/CABM-pytorch/commit/07c2707abfc132a7677a46d7a1aa8d03d7eff4c0)
> 
>  with open(f'{args.model}-{args.scale}-{args.data_test}.json','w') as f:

您好，按照Step1训练的时候就会报没有这个文件的错误，是不是可以先注释掉不用管。

![Image](https://github.com/user-attachments/assets/d9564a41-e613-4bf5-a9ed-36a1e9ae7778)

**Comment by Sheldon04** [comment]
> > 您好！ 这个文件我没有放上去，您可以先读一下论文，然后按照步骤训练模型，到第四步的时候，运行对应的脚本就可以生成这个文件了！ 这里是保存这个文件的代码：
> > [CABM-pytorch/main_getconfig.py](https://github.com/Sheldon04/CABM-pytorch/blob/07c2707abfc132a7677a46d7a1aa8d03d7eff4c0/main_getconfig.py#L683)
> > Line 683 in [07c2707](/Sheldon04/CABM-pytorch/commit/07c2707abfc132a7677a46d7a1aa8d03d7eff4c0)
> > with open(f'{args.model}-{args.scale}-{args.data_test}.json','w') as f:
> 
> 您好，按照Step1训练的时候就会报没有这个文件的错误，是不是可以先注释掉不用管。
> 
> ![Image](https://github.com/user-attachments/assets/d9564a41-e613-4bf5-a9ed-36a1e9ae7778)

您好，抱歉对这个问题的疏忽，我已经注释掉错误的部分了
