### ISSUE TITLE
question for student network

### ISSUE THREAD

**Issue by vokkko** [Sheldon04/CABM-pytorch#5]
It's a nice work! Can I just use the student and teacher networks edsr_×4_pams_w8a8.pt which provided in CADyQ from Google Cloud to train the edsrbaseline_cabm_simple?

**Comment by Sheldon04** [comment]
Thanks for your interest! You can use all models provided by CADyQ and just
make sure that the model structure is correct.

vokkko ***@***.***> 于 2023年10月8日周日 21:59写道：

**Comment by vokkko** [comment]
I first use the student and techer networks to train the edsr_cadyq. When I  tried to train_edsrbaselin_cabm_simple using the same student and teacher networks, it came to wrong. :( 
I checked the number of resblocks, it was 16. I don't know where i make mistakes.
Traceback (most recent call last):
  File "main_inference.py", line 793, in <module>
    main()
  File "main_inference.py", line 774, in main
    s_model.load_state_dict(s_checkpoint)
  File "/home/u2023110503/.conda/envs/CADyQ/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EDSR_CADyQ_I:
        Missing key(s) in state_dict: "body.0.bitsel1.quant_bit1.alpha", "body.0.bitsel1.quant_bit1.max_val"......
        Unexpected key(s) in state_dict: "body.0.quant_act1.alpha", "body.0.quant_act1.max_val",......

**Comment by vokkko** [comment]
If I set the student network to None, it can train correctly.

**Comment by Sheldon04** [comment]
Oh, sorry for the bug. Actually, the student weights should be from part of a pretrained CADyQ model. So one way is to load PAMS weights and set the param 'strict' to False and athother way is to load the CADyQ weights. I will fix it. Thanks for your carefulness. BTW, if you set the student network to None, the final result may not be particularly ideal.

**Comment by vokkko** [comment]
Thanks for your reply!
